name: Build Docker images

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  alpine-amd64:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          context: alpine
          push: true
          tags: ghcr.io/1ma/alpine-amd64:latest
          cache-from: type=registry,ref=ghcr.io/1ma/alpine-amd64:latest
          cache-to: type=inline

  alpine-arm64:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v5
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          context: alpine
          push: true
          tags: ghcr.io/1ma/alpine-arm64:latest
          cache-from: type=registry,ref=ghcr.io/1ma/alpine-arm64:latest
          cache-to: type=inline

  alpine-merge:
    runs-on: ubuntu-24.04
    needs:
      - alpine-amd64
      - alpine-arm64
    steps:
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Create manifest list and push
        run: |
          docker buildx imagetools create \
            -t ghcr.io/1ma/alpine2:latest \
            ghcr.io/1ma/alpine-amd64:latest \
            ghcr.io/1ma/alpine-arm64:latest
